"CI/CD":
  - all:
      - ".github/workflows/**"

"Maintenance":
  - all:
      - ".github/**"
      - "!.github/workflows/**"

"tests":
  - all:
      - "tests/**"

"docs":
  - any:
      - "docs/**"
