"CI/CD":
  - all:
      - changed-files:
          - any-glob-to-any-file:
              - ".github/workflows/**"
              - "tox.ini"
              - ".yamllint.yml"

"Maintenance":
  - all:
      - changed-files:
          - any-glob-to-any-file:
              - ".github/*"
              - ".github/ISSUE_TEMPLATE/*"

"tests":
  - all:
      - changed-files:
          - any-glob-to-any-file:
              - "tests/**"

"docs":
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "docs/**"
              - "examples/**"
              - "README.rst"

"Widget":
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "urwid/widget/**"
              - "urwid/numedit.py"
              - "urwid/vterm.py"

"Display":
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "urwid/display/**"

"Event loop":
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "urwid/event_loop/**"

"Canvas":
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "urwid/canvas.py"
