"CI/CD":
  - all:
      - ".github/workflows/**"

"Maintenance":
  - all:
      - ".github/**"
      - "!.github/workflows/**"

"docs":
  - any:
      - "docs/**"
      - "examples/**"
      - "README.rst"
