[tox]
requires =
  tox>=4
  tox-uv>=1
envlist = py3{9,10,11,12,13,14},pypy3,ruff,pylint,mypy,refurb
skip_missing_interpreters = True

[testenv]
usedevelop = true
dependency_groups = pytest
extras =
  curses
  serial
  tornado
  trio
  twisted
  zmq

commands =
  pytest

[testenv:readme]
dependency_groups = build
extras =
commands =
  python -m build
  twine check {toxinidir}/dist/*

[testenv:ruff]
skip_install = true
depends =
dependency_groups = ruff
extras =
commands =
  ruff format --check .
  ruff check .

[testenv:docs]
dependency_groups = documentation
extras =
  {[testenv]extras}
  glib
commands = sphinx-build docs/ build/documentation

[testenv:pylint]
depends = ruff
dependency_groups = pylint
extras =
  {[testenv]extras}
  glib
commands = pylint urwid

[testenv:refurb]
depends = ruff
deps = refurb
extras =
commands = refurb urwid examples

[testenv:mypy]
depends = ruff
dependency_groups = mypy
commands = mypy urwid
