from typing import Tuple

def calc_text_pos(text: str, start_offs: int, end_offs: int, pref_col: int) -> Tuple[int, int]: ...
def calc_width(text: str, start_offs: int, end_offs: int) -> int: ...
def decode_one(text: str, pos: int) -> Tuple[int, int]: ...
def decode_one_right(text: str, pos: int) -> Tuple[int, int]: ...
def get_byte_encoding() -> str: ...
def get_width(o: int) -> int: ...
def is_wide_char(text: str, offs: int) -> bool: ...
def move_prev_char(text: str, start_offs: int, end_offs: int) -> int: ...
def move_next_char(text: str, start_offs: int, end_offs: int) -> int: ...
def set_byte_encoding(enc: str) -> None: ...
def within_double_byte(text: str, line_start: int, pos: int) -> int: ...
