name: Isolated Mypy check

on:
  pull_request:
    paths:
      - "mypy-requirements.txt"
      - ".github/workflows/isolated_mypy.yml"

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  Mypy:
    name: Check with mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.x'
      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1
      - name: Create virtual environment
        run: uv venv --python-preference only-system
      - name: Install package with all extras
        run: uv pip install -e ".[curses,serial,tornado,trio,twisted,zmq]"
      - name: Install dependencies
        run: uv pip install --upgrade -r mypy-requirements.txt
      - name: Type check with mypy
        run: uv run --no-project mypy urwid
