name: Lint YAML

on:
  pull_request:
    paths:
      - "**.yml"
      - "**.yaml"
      - "yamllint-requirements.txt"

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1
      - name: Lint YAML files
        run: uv run --no-project --with-requirements yamllint-requirements.txt yamllint . -f github
