name: Lint YAML

on:
  pull_request:
    paths:
      - "**.yml"
      - "**.yaml"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1
      - name: Lint YAML files
        run: uvx yamllint . -f github
